### ISSUE TITLE
Android SDK NullPointerException

### ISSUE THREAD

**Issue by kmvignesh** [Instamojo/android-sdk#32]
The payment process is working fine when we have proper internet.
But when I disconnected internet(for testing) then calling "callInstamojoPay", making the app to crashed due to NPE.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
        at instamojo.library.Instamojo$1.onResponse(Instamojo.java:115)
        at instamojo.library.API.AccessToken$AccessTokenAsyn.onPostExecute(AccessToken.java:46)
        at instamojo.library.API.AccessToken$AccessTokenAsyn.onPostExecute(AccessToken.java:25)
```

Also if network goes down and comes also the app is crashing 

```
 java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
        at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
        at org.json.JSONTokener.nextValue(JSONTokener.java:94)
        at org.json.JSONObject.<init>(JSONObject.java:159)
        at org.json.JSONObject.<init>(JSONObject.java:176)
        at instamojo.library.Instamojo$2.onResponse(Instamojo.java:185)
```

*The payment process is working fine when we have proper internet.

**Comment by kmvignesh** [comment]
No, I contacted instamojo people, the days it will crash if internet connection get disconnected.

**Comment by mohammadjannaser** [comment]
Just change your URL from http to https in the manifest file this problem will be solved

**Comment by vinaykumar2197** [comment]
To support urls in android 9 .Due to security reasons , **http** must be replaced with **https** . 

CHANGE (in manifest)  : 

 **<meta-data
            android:name="instamojo.orderauth.url"
            android:value="**http:**//abc.com/access_token.php" />**

to  

 **<meta-data
            android:name="instamojo.orderauth.url"
            android:value="**https:**//abc.com/access_token.php" />**

compile and run

**Comment by vinaykumar2197** [comment]
To support urls in android 9 .Due to security reasons , http must be replaced with https . 

CHANGE ( in manifest ) : 

 <meta-data
            android:name="instamojo.orderauth.url"
            **android:value="http://abc.com/access_token.php"** />

to  

 <meta-data
            android:name="instamojo.orderauth.url"
            **android:value="https://abc.com/access_token.php"** />

compile and run
